<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Creates demo DOCX template files for the tutorial page.
 */
class DG_Demo {

    /**
     * Get the path to a demo template, creating it if needed.
     *
     * @param string $type 'simple' or 'table'.
     * @return string Path to the demo file.
     */
    public static function get_demo_path( $type ) {
        $dir = DG_PLUGIN_DIR . 'assets/demos/';
        wp_mkdir_p( $dir );

        $file = $dir . 'demo-' . $type . '.docx';

        if ( ! file_exists( $file ) ) {
            if ( 'simple' === $type ) {
                self::create_simple_demo( $file );
            } elseif ( 'table' === $type ) {
                self::create_table_demo( $file );
            }
        }

        return $file;
    }

    /**
     * Create simple demo template (user profile with formatting).
     */
    private static function create_simple_demo( $filepath ) {
        $body_xml = '
        <w:p>
            <w:pPr><w:pStyle w:val="Title"/></w:pPr>
            <w:r><w:t>User Profile Document</w:t></w:r>
        </w:p>
        <w:p>
            <w:pPr><w:pStyle w:val="Subtitle"/></w:pPr>
            <w:r><w:t>Generated by WPDocxGen</w:t></w:r>
        </w:p>
        <w:p><w:r><w:t xml:space="preserve"> </w:t></w:r></w:p>
        <w:p>
            <w:pPr><w:pStyle w:val="Heading1"/></w:pPr>
            <w:r><w:t>Personal Information</w:t></w:r>
        </w:p>
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">Full Name: </w:t></w:r>
            <w:r><w:t>#user_firstname# #user_lastname#</w:t></w:r>
        </w:p>
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">Display Name: </w:t></w:r>
            <w:r><w:t>#display_name#</w:t></w:r>
        </w:p>
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">Email: </w:t></w:r>
            <w:r><w:t>#user_email#</w:t></w:r>
        </w:p>
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">Role: </w:t></w:r>
            <w:r><w:t>#user_role#</w:t></w:r>
        </w:p>
        <w:p><w:r><w:t xml:space="preserve"> </w:t></w:r></w:p>
        <w:p>
            <w:pPr><w:pStyle w:val="Heading1"/></w:pPr>
            <w:r><w:t>Site Information</w:t></w:r>
        </w:p>
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">Site Name: </w:t></w:r>
            <w:r><w:t>#site_name#</w:t></w:r>
        </w:p>
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">Site URL: </w:t></w:r>
            <w:r><w:t>#site_url#</w:t></w:r>
        </w:p>
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">Generated on: </w:t></w:r>
            <w:r><w:t>#current_date#</w:t></w:r>
        </w:p>
        ';

        self::write_docx( $filepath, $body_xml );
    }

    /**
     * Create table demo template (users list in a table).
     */
    private static function create_table_demo( $filepath ) {
        $body_xml = '
        <w:p>
            <w:pPr><w:pStyle w:val="Title"/></w:pPr>
            <w:r><w:t>Users Report</w:t></w:r>
        </w:p>
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">Site: </w:t></w:r>
            <w:r><w:t>#site_name#</w:t></w:r>
        </w:p>
        <w:p>
            <w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">Generated: </w:t></w:r>
            <w:r><w:t>#current_date#</w:t></w:r>
        </w:p>
        <w:p><w:r><w:t xml:space="preserve"> </w:t></w:r></w:p>
        <w:tbl>
            <w:tblPr>
                <w:tblStyle w:val="TableGrid"/>
                <w:tblW w:w="5000" w:type="pct"/>
                <w:tblBorders>
                    <w:top w:val="single" w:sz="4" w:space="0" w:color="000000"/>
                    <w:left w:val="single" w:sz="4" w:space="0" w:color="000000"/>
                    <w:bottom w:val="single" w:sz="4" w:space="0" w:color="000000"/>
                    <w:right w:val="single" w:sz="4" w:space="0" w:color="000000"/>
                    <w:insideH w:val="single" w:sz="4" w:space="0" w:color="000000"/>
                    <w:insideV w:val="single" w:sz="4" w:space="0" w:color="000000"/>
                </w:tblBorders>
            </w:tblPr>
            <w:tblGrid>
                <w:gridCol w:w="600"/>
                <w:gridCol w:w="2500"/>
                <w:gridCol w:w="3000"/>
                <w:gridCol w:w="1500"/>
            </w:tblGrid>
            <w:tr>
                <w:tc>
                    <w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="2B579A"/></w:tcPr>
                    <w:p><w:r><w:rPr><w:b/><w:color w:val="FFFFFF"/></w:rPr><w:t>#</w:t></w:r></w:p>
                </w:tc>
                <w:tc>
                    <w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="2B579A"/></w:tcPr>
                    <w:p><w:r><w:rPr><w:b/><w:color w:val="FFFFFF"/></w:rPr><w:t>Name</w:t></w:r></w:p>
                </w:tc>
                <w:tc>
                    <w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="2B579A"/></w:tcPr>
                    <w:p><w:r><w:rPr><w:b/><w:color w:val="FFFFFF"/></w:rPr><w:t>Email</w:t></w:r></w:p>
                </w:tc>
                <w:tc>
                    <w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="2B579A"/></w:tcPr>
                    <w:p><w:r><w:rPr><w:b/><w:color w:val="FFFFFF"/></w:rPr><w:t>Role</w:t></w:r></w:p>
                </w:tc>
            </w:tr>
            <w:tr>
                <w:tc><w:p><w:r><w:t>#repeat:users# #index#</w:t></w:r></w:p></w:tc>
                <w:tc><w:p><w:r><w:t>#display_name#</w:t></w:r></w:p></w:tc>
                <w:tc><w:p><w:r><w:t>#user_email#</w:t></w:r></w:p></w:tc>
                <w:tc><w:p><w:r><w:t>#user_role# #endrepeat#</w:t></w:r></w:p></w:tc>
            </w:tr>
        </w:tbl>
        <w:p><w:r><w:t xml:space="preserve"> </w:t></w:r></w:p>
        <w:p>
            <w:r><w:rPr><w:i/><w:sz w:val="20"/></w:rPr>
            <w:t>This document was automatically generated by WPDocxGen plugin.</w:t></w:r>
        </w:p>
        ';

        self::write_docx( $filepath, $body_xml );
    }

    /**
     * Write a minimal valid DOCX file.
     */
    private static function write_docx( $filepath, $body_xml ) {
        $zip = new ZipArchive();
        if ( true !== $zip->open( $filepath, ZipArchive::CREATE | ZipArchive::OVERWRITE ) ) {
            return;
        }

        // [Content_Types].xml
        $zip->addFromString( '[Content_Types].xml', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
    <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
    <Default Extension="xml" ContentType="application/xml"/>
    <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
    <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>' );

        // _rels/.rels
        $zip->addFromString( '_rels/.rels', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>' );

        // word/_rels/document.xml.rels
        $zip->addFromString( 'word/_rels/document.xml.rels', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>' );

        // word/styles.xml (defines Title, Subtitle, Heading1 styles)
        $zip->addFromString( 'word/styles.xml', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
    <w:style w:type="paragraph" w:styleId="Title">
        <w:name w:val="Title"/>
        <w:pPr><w:jc w:val="center"/></w:pPr>
        <w:rPr><w:b/><w:sz w:val="56"/><w:color w:val="2B579A"/></w:rPr>
    </w:style>
    <w:style w:type="paragraph" w:styleId="Subtitle">
        <w:name w:val="Subtitle"/>
        <w:pPr><w:jc w:val="center"/></w:pPr>
        <w:rPr><w:i/><w:sz w:val="28"/><w:color w:val="666666"/></w:rPr>
    </w:style>
    <w:style w:type="paragraph" w:styleId="Heading1">
        <w:name w:val="heading 1"/>
        <w:rPr><w:b/><w:sz w:val="32"/><w:color w:val="2B579A"/></w:rPr>
    </w:style>
    <w:style w:type="table" w:styleId="TableGrid">
        <w:name w:val="Table Grid"/>
        <w:tblPr>
            <w:tblBorders>
                <w:top w:val="single" w:sz="4" w:space="0" w:color="auto"/>
                <w:left w:val="single" w:sz="4" w:space="0" w:color="auto"/>
                <w:bottom w:val="single" w:sz="4" w:space="0" w:color="auto"/>
                <w:right w:val="single" w:sz="4" w:space="0" w:color="auto"/>
                <w:insideH w:val="single" w:sz="4" w:space="0" w:color="auto"/>
                <w:insideV w:val="single" w:sz="4" w:space="0" w:color="auto"/>
            </w:tblBorders>
        </w:tblPr>
    </w:style>
</w:styles>' );

        // word/document.xml
        $zip->addFromString( 'word/document.xml', '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas"
            xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
            xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
    <w:body>' . $body_xml . '
        <w:sectPr>
            <w:pgSz w:w="12240" w:h="15840"/>
            <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/>
        </w:sectPr>
    </w:body>
</w:document>' );

        $zip->close();
    }
}
